# Jekyll
permalink:       /:categories/:year/:title/
url:             http://camerongarrett.com
exclude:         ['README.md', 'Gemfile', 'Guardfile', 'Rakefile', '_resources/']

# Rakefile
blog:
  template:      _templates/blog.txt
  extension:     md
work:
  template:      _templates/work.txt
  extension:     md

# Site Map - the exclude is not working
# https://github.com/danielgroves/jekyll-plugins
sitemap:
    exclude: "/assets/css/style.css"
